name: reveal-pdf
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Create "/slides" directory
        run: mkdir slides && sudo chmod 777 slides

      - name: Build PDF
        run: docker run --rm -t -v `pwd`:/slides -v ~:/home/user astefanutti/decktape index.html presentation.pdf

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1
